### ISSUE TITLE
Navigation bar freeze when scroll down

### ISSUE THREAD

**Issue by lukaning** [bodhiproject/white-papers#1]
![screen shot 2017-08-02 at 8 16 22 pm](https://user-images.githubusercontent.com/3132652/28904392-7e32f584-77bf-11e7-8174-3980dfa39568.png)

导航栏需要固定在顶部

**Comment by chrisli30** [comment]
Issue fixed

**Comment by chrisli30** [comment]
This is a website issue and has been fixed
